### ISSUE TITLE
How to submit new plugin we have built for Gocd

### ISSUE THREAD

**Issue by volodymyr-mykhailyk** [gocd/gocd-plugin-info#29]
Hi There,

we have built simple notification plugin and while browsing documentation wasn't able to find how to submit the plugin to be added to the plugin list. 

Is this repository is the directory of plugins? Should I create PR? How does plugin review works?

**Comment by bdpiparva** [comment]
@volodymyr-mykhailyk - The plugin list is populated from yaml files listed [here](https://github.com/gocd/www.go.cd/tree/master/data/plugins). Please submit the PR to  https://github.com/gocd/www.go.cd repo, once PR is merged the plugin will be listed of official plugin listing [page](https://www.gocd.org/plugins/) and also here.

**Comment by volodymyr-mykhailyk** [comment]
Thanks!
